##################################################
##  STAGES
##################################################

stages:
  - test

.docker_runner: &docker_runner
  tags:
    - autoscaler


##################################################
##  BRANCH TEMPLATES
##################################################

.release_branch_ci: &release_branch_ci
  only:
    - release@ai/orca
    - /^patch.*$/@ai/orca
  before_script:
    - export VERSION=$(grep '__version__ =' src/__init__.py | awk -F ' ' '{print $3}' | sed -e "s/^'//" -e "s/'$//")

.master_branch_ci: &master_branch_ci
  only:
    - master@ai/orca
  before_script:
    - export VERSION=$(grep '__version__ =' src/__init__.py | awk -F ' ' '{print $3}' | sed -e "s/^'//" -e "s/'$//")-alpha

.feature_branch_ci: &feature_branch_ci
  only:
    - branches
  except:
    - /^nobuild-.*/
    - master@ai/orca
    - release@ai/orca
    - /^patch.*$/@ai/orca
  before_script:
    - export VERSION=$(grep '__version__ =' src/__init__.py | awk -F ' ' '{print $3}' | sed -e "s/^'//" -e "s/'$//")-${CI_COMMIT_REF_NAME}

##################################################
##  TEST
##################################################

.test_template: &test_template
  <<: *docker_runner
  image: eu1dv1acs.azurecr.io/devops/ci/miniconda:3
  stage: test
  script:
    - mkdir -p ~/.certificates && cat $WILDCARD_INNOVATE_CRT > ~/.certificates/innovate.pem
    - mkdir -p ~/.config/pip && cat $PIP_CONF > ~/.config/pip/pip.conf
    - USER_ROOT=$(echo ~ | sed 's_/_\\/_g') && sed -i -e "s/\/root/$USER_ROOT\/.certificates/" ~/.config/pip/pip.conf
    - ./app setup-environment
    - ./app lint-test
#    - ./app unit-test
#  coverage: '/\d+?%/'
  after_script:
    - ./app delete-environment

.artifact_template:
  artifacts: &artifact_template
    reports:
      cobertura: coverage.xml
    paths:
      - coverage.xml

.long_expiry:
  artifacts: &long_expiry
#    <<: *artifact_template
    expire_in: 1 years

.short_expiry:
  artifacts: &short_expiry
#    <<: *artifact_template
    expire_in: 2 hours

test_feature_branch:
  <<: *test_template
  <<: *feature_branch_ci
  artifacts:
    <<: *short_expiry

test_master:
  <<: *test_template
  <<: *master_branch_ci
  artifacts:
    <<: *long_expiry

test_release:
  <<: *test_template
  <<: *release_branch_ci
  artifacts:
    <<: *long_expiry

