name: clpt
channels:
  - defaults
  - conda-forge
dependencies:
  - blist==1.3.6
  - pip=20.2.2
  - python=3.7.13
  - pip:
    - antlr4-python3-runtime==4.8
    - attrs==21.4.0
    - cached_property==1.5.2
    - coverage==5.5
    - cython==0.29.29
    - flake8==3.8.4
    - func-timeout==4.3.5
    - future==0.18.2
    - gensim== 3.8.3 
    - hydra-core==1.1.1
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - jinja2==2.10.1
    - lxml==4.8.0
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - medspacy==0.2.0.0
    - more-itertools==8.12.0
    - nltk==3.7
    - numpy==1.21.6
    - omegaconf==2.1.1
    - overrides==6.1.0
    - packaging==21.3
    - pandas==1.3.5
    - pluggy==0.13.1
    - py==1.11.0
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - pyspellchecker==0.6.3
    - pyparsing==3.0.8
    - pytest==5.4.3
    - pytest-cov==2.9.0
    - pytest-mock==3.3.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - recommonmark==0.6.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - scispacy==0.5.0
    - six==1.16.0
    - spacy==3.1.6
    - sphinx==3.1.1
    - sphinx_rtd_theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - typing-extensions==4.1.1
    - wcwidth==0.2.5
    - zipp==3.6.0
