defaults:
  - ingestion: default
  - analysis: default
  - classification: default
pipeline_stages:
  - type: SpaCyProcessing
    pos: True
    lemma: True
    break_sentences: True
  - type: PorterStemming


