defaults:
  - ingestion: default
  - analysis: default
  - classification: default
pipeline_stages:
  - type: RemoveStopWord
    # add params here
  - type: ConvertToLowerCase
  - type: ExcludePunctuation
#  - type: SentenceBreaking
  - type: RegexTokenization
  - type: PorterStemming
  - type: SpaCyLemma #WordnetLemma


