from enum import Enum

ANNOTATION = 'annotation'
CLEANED_TEXT = 'cleaned_text'
DESCRIPTION = 'description'
EMBEDDING = 'embedding'
EMBEDDING_ID = 'embedding_id'
ENTITIES = 'entities'
ENTITY = 'entity'
ENTITY_GROUP = 'entity_group'
ELEMENT = 'element'
HEADING = 'heading'
ID = 'id'
LEMMA = 'lemma'
LITERAL = 'literal'
PARAGRAPH = 'paragraph'
PARAGRAPHS = 'paragraphs'
POS = 'pos'
RAW_TEXT = 'raw_text'
SECTION = 'section'
SENTENCE = 'sentence'
SENTENCES = 'sentences'
SPAN = 'span'
SPELL_CORRECTED_TOKEN = 'spell_corrected_token'
STEM = 'stem'
TEXT = 'text'
TEXT_ELEMENT = 'text'
TOKEN = 'token'
TOKENS = 'tokens'
VECTOR = 'vector'


class EntityType(Enum):
    """Types of Entities in a TextCLAO"""
    FACT = 'FACT'
    MENTION = 'MENTION'
    NER = 'NER'
