pipeline_stages:
  # add params here
  - type: RemoveStopWord
  - type: ConvertToLowerCase
  - type: ExcludePunctuation
  - type: SentenceBreaking
  - type: RegexTokenization
  - type: SpellCorrectLevenshtein
  - type: PorterStemming
#  - type: SpaCyLemma
